config/routes.rb
Twitter::Application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations'}
  root "static_pages#welcome"

  resources :tweets, only: [:create, :destroy]
  resources :users, only: [:index, :show]

  get "/about" => "static_pages#about", as: :about
  get "/terms-of-service" => "static_pages#tos", as: :terms_of_service
  get "/privacy-policy" => "static_pages#privacy", as: :privacy_policy
  get "/newsletter" => "static_pages#newsletter"
  post "/newsletter" => "static_pages#newsletter"

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base

  after_create :newsletter_email

  private

  def newsletter_email
    UserMailer.newsletter(self).deliver
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :age, :username, :password, :password_confirmation)}
  end

 def after_sign_in_path_for(resource)
    user_path(current_user)
  end



end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  protected

  def after_sign_up_path_for(resource)
    
    UserMailer.welcome(@user).deliver
    user_path(@user)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  layout 'twitter'

  def welcome
  #   UserMailer.welcome(current_user).deliver
  #   redirect_to root_path, notice: 'welcome'
  end

  def about
  end

  def tos
  end

  def privacy
  end

  def newsletter
    @newsletter = Newsletter.new
    if request.post?
      @newsletter.assign_attributes(newsletter_params)
      @newsletter.save
      redirect_to root_path, notice: 'thanks for signing up'
    end
  end

  private

  def newsletter_params
    params.require(:newsletter).permit(:newsletter_email)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      flash[:succes] = 'You have created a new tweet'
      redirect_to user_path(current_user)
    else
      flash[:error] = 'Your tweet was not created.'
      redirect_to user_path(current_user)
    end
  end

  def destroy
    @tweet.destroy
    flash[:notice] = 'That tweet was removed.'
    redirect_to user_path(current_user)
  end

  def show
    @tweet = Tweet.all  
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content, :user_id)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = current_user
    @tweet = @user.tweets.build
    @tweets = Tweet.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def user_logged_in?
    user_signed_in?
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Twitter" %></title>
    <%= csrf_meta_tags %>
   <!-- <p class="notice"><%= notice %></p> -->
   <!-- <p class="alert"><%= alert %></p> -->
 

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Twitter</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <% if user_logged_in? %>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
                <li><%= link_to "My Account", edit_user_registration_path   %></li>
              <% else %>
                <li><%= link_to "Login", new_user_session_path  %></li>
                <li><%= link_to "Signup", new_user_registration_path  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
  
          
        <%= yield %>
           
        <%= bootstrap_flash %>
          
      

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/twitter.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Twitter" %></title>
    <%= csrf_meta_tags %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">

      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>

          </a>
          <a class="brand" href="<%= root_path %>"><span class="icon icon-home">  Home</a>

          <a class="brand" href="<%= root_path %>"><span class="icon icon-twitter"></a>

          <div class="container-fluid nav-collapse pull-right">
            <nav>
              <a class="brand" href="<%= root_path %>">
                <span class="icon icon-cog">
              </a>
                  <ul>
                    <li><a href="#">Test1</a></li>
                  </ul>
            </nav>
            <ul class="nav">
            
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

      </div><!--/span-->
       <div class="offset1 span6">
          <div class="well sidebar-nav">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div>
      </div><!--/row-->

      <div class="container-fluid">
        <div class="row-fluid">
          <div class="offset1 span3">
            <div class="well sidebar-nav">
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                  <h2>Sign in</h2>
                  <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
                  <div><%= f.label :email %><br />
                  <%= f.email_field :email, :autofocus => true %></div>
                  <div><%= f.label :password %><br />
                  <%= f.password_field :password %></div>
                  <% if devise_mapping.rememberable? -%>
                    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
                  <% end -%>
                  <div id="sign_in_btn"><%= f.submit "Sign in" %></div>
                <% end %>
              </ul>
            </div><!--/.well -->
            <div class="well sidebar-nav">
              <h2>Sign up</h2>

              <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
                <%= devise_error_messages! %>

                <div><%= f.label :email %><br />
                <%= f.email_field :email %></div>

                <div><%= f.label :password %><br />
                <%= f.password_field :password %></div>

                <div><%= f.label :password_confirmation %><br />
                <%= f.password_field :password_confirmation %></div>

                <div><%= f.submit "Sign up" %></div>
              <% end %>
            </div>
      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div> <!-- /container -->

   
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/index.html.erb
<h1 class="page-header">Welcome to Twitter</h1>

<div class="control-group">
  <%= image_tag('twitter.jpeg', class: 'pull-right') %>
</div>

app/views/static_pages/newsletter.html.erb
<h1 class="page-header">Sign Up for Our Newsletter</h1>

<%= form_for(@newsletter, url: newsletter_path) do |f| %>
  <%= f.text_field(:newsletter_email, placeholder: 'Email') %><br>
  <%= f.submit('Sign Up', class: 'btn btn-success') %>

<% end %>

app/views/static_pages/privacy.html.erb
<h1>StaticPages#privacy</h1>
<p>Find me in app/views/static_pages/privacy.html.erb</p>

app/views/static_pages/tos.html.erb
<h1>StaticPages#tos</h1>
<p>Find me in app/views/static_pages/tos.html.erb</p>

app/views/static_pages/welcome.html.erb
<h1 class="page-header">Welcome to Twitter</h1>

<ul class="nav">
  <li><%= link_to "Newsletter Signup", newsletter_path  %></li>
</ul>  
<div class="control-group">
  
</div>

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/users/show.html.erb
<h1>My Tweets </h1>
<h4><%= current_user.email %></h4>
<br>


<div class="span9">
  <div class="well sidebar-nav">
    <% @tweets.each do |tweet| %><p>
      <%= tweet.content %>
    <% end %>

  </div><!--/.well -->
</div><!--/span-->


    <div class="row-fluid">
        <div class="span3 offset1">
          <div class="well sidebar-nav">
            <%= form_for(@tweet) do |f| %>
              <p><%= f.text_field (:content) %></p>
              <div><%= f.submit("Tweet Now") %></div>
            <% end %>

          </div><!--/.well -->
        </div><!--/span-->
      </div>